### ISSUE TITLE
Cannot load Youtube Viewer on Linux Mint 17.3

### ISSUE THREAD

**Issue by disk4mat** [trizen/youtube-viewer#124]
I have been trying to get youtube viewer to load on linux  mint but i get  nothing and searching for a solution did nothing, any help?

**Comment by trizen** [comment]
For Linux Mint and Ubuntu there is an unofficial package which can be installed invoking the following commands:

```bash
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install youtube-viewer
```

after which youtube-viewer (the CLI version) can be invoked as:

```bash
youtube-viewer
```

and for the GTK version, we have:

```bash
gtk-youtube-viewer
```

Try this to see if it works, and if you encounter any error messages, please copy-paste them here for further investigation.

**Comment by disk4mat** [comment]
Thanks for the reply, those are the steps i took to install it.
when i try to open it in a terminal with gtk-youtube-viewer i get 
`"all" is not exported by the List::Util module
Can't continue after import errors at /usr/bin/gtk-youtube-viewer line 40.
BEGIN failed--compilation aborted at /usr/bin/gtk-youtube-viewer line 40.
`
And when i try with "youtube-viewer" it opens up the app inside terminal.

**Comment by trizen** [comment]
It seems like the [List::Util](https://metacpan.org/pod/List::Util) Perl module is a little bit out-of-date. (the `"all"` function is available starting with version 1.33).

I don't have much experience with Linux Mint, but if there is a way to update `libscalar-list-utils-perl` to a newer version (>=1.33) should fix the issue.

Otherwise, try this command:
```bash
sudo perl -MCPAN -e 'CPAN::Shell->install(q{List::Util})'
```

**Comment by ZhiRey** [comment]
Thank you so much , all weekend I spend looking for a solution until I found this forum .
Waiter , serve a beer to trizen , he deserves =)

**Comment by disk4mat** [comment]
Did you try the command suggested by trizen? I've tried his suggestions but still cannot get it to load...

**Comment by trizen** [comment]
I'm sorry about that, @disk4mat. The commit https://github.com/trizen/youtube-viewer/commit/d2944eea88f56892fe90587a705bb6c6db553052, which will be available in the next version, should fix this issue.

**Comment by trizen** [comment]
Fixed in version 3.2.4: https://github.com/trizen/youtube-viewer/releases/tag/3.2.4
