### ISSUE TITLE
youtube-viewer is reallys slow

### ISSUE THREAD

**Issue by Hund** [trizen/youtube-viewer#93]
Why does this take 18 seconds?

http://hastebin.com/uhunohivim

It's been like this for a month or two now I think. :( There is nothing wrong on my internet (fiber) connection.

I dont know how to further debug this?

**Comment by trizen** [comment]
It's an YouTube issue, unfortunately. (see: https://code.google.com/p/gdata-issues/issues/detail?id=3946).

youtube-viewer tries to do something about it, but the algorithm that is uses makes many requests before it gets and displays the subscriptions, which are messed up anyway. (see: https://github.com/trizen/youtube-viewer/issues/74)

Any improvements are welcome: https://github.com/trizen/youtube-viewer/blob/master/lib/WWW/YoutubeViewer/Subscriptions.pm#L63

**Comment by Hund** [comment]
Ah! Thank you. :)

**Comment by trizen** [comment]
No problem. ;)

**Comment by trizen** [comment]
The problem has been fixed (partially). Now, the `-S` option displays the subscribed channels instead. See: https://github.com/trizen/youtube-viewer/commit/aff24e520b182dd498422eb5d4c2906c36273595

**Comment by Hund** [comment]
What do you mean by partially?

**Comment by trizen** [comment]
The `-SV` option  (which displays subscription videos) is still slow, so the problem is not entirely fixed in this regard, but because of the new behavior of `-S`, the first option may be redundant.

**Comment by Hund** [comment]
I see. :) You forgot to change the gtk version I think. It shows the
channels for me now, not the latest videos.

**Comment by trizen** [comment]
No, no, this is the new behavior. :)

**Comment by Hund** [comment]
What's the point with showing channels and not being able to view the
latest videos? :P

**Comment by trizen** [comment]
Now the user can choose any channel to view the latest uploads from it. It's a simpler system which actually works correctly and it's faster too.

**Comment by Hund** [comment]
Would you consider adding a option to get the old behavior back? I don't
like the new way. :D

**Comment by Hund** [comment]
I'm not trying to bash on you now. But how is the new way a better option? Whats the point with showing the channels I am subscribed to? The only thing I can do now is to open the channel in my browser via the application and then browse the videos I want to see. I really dont think thats easier in any way possible. It makes the whole application redundant. :)

**Comment by trizen** [comment]
You can double-click any channel to view the latest uploads from it. Currently, there is no way to revert to the old behavior.

**Comment by trizen** [comment]
I would consider adding another button to get the subscription videos.

**Comment by Hund** [comment]
Oh. I see. I tried that before, but it didnt do anything so I just assumed that was the new default behavior.

Thank you! It's not a major issue. I can still use the CLI version. But I find it easier to just look at the thumbnails rather than reading the title and the channel name. :)
